# Natural Language Processing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Restaurant_reviews.csv')

In [3]:
dataset.shape

(9955, 7)

## Cleaning the texts

In [4]:

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stopwords = set(stopwords.words('english'))
stopwords.remove('not')

corpus = []
y = []
for i in range(len(dataset)):
  review = dataset['Review'][i]
  if type(review) == str:
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(item) for item in review if not item in stopwords]
    review = ' '.join(review)
    corpus.append(review)
    y.append(dataset['Rating'][i])
  

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
len(corpus)

9955

## Creating the Bag of Words model

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=10500)
X = cv.fit_transform(corpus).toarray()
# y = dataset['Rating'].values

In [7]:
len(X[0])

10500

## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

## Training the Naive Bayes model on the Training set

In [9]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

## Predicting the Test set results

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((np.array(y_pred).reshape(len(y_pred),1), np.array(y_test).reshape(len(y_test),1)),1))

[[3 5]
 [1 2]
 [1 2]
 ...
 [3 2]
 [4 5]
 [4 3]]


## Making the Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[293   4  20  23  12]
 [ 65   5  35  29   3]
 [ 35   5  59 117  20]
 [ 13   2  23 309 162]
 [ 13   0   8 155 581]]


0.6263184329482672

## Predicting if a review is positive or negative

In [25]:
new_review = input("Enter your review: ")
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
new_review = [ps.stem(word) for word in new_review if not word in stopwords]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred[0])

Enter your review: it was ok
3
